name: Verify that build is not broken
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  verify:
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build Android sample app
        run: ./gradlew androidApp:assembleDebug
      - name: Build .xcf
        run: ./gradlew assemblePvbaXCFramework